# Generated by Django 3.0.7 on 2020-06-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200619_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='boxoffice',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbrating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbvotes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='metascore',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
    ]
