# Generated by Django 3.0.7 on 2020-06-19 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200619_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('series', 'series'), ('episode', 'episode')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
