# Generated by Django 3.0.7 on 2020-06-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovielist',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='MovieOnList',
        ),
        migrations.DeleteModel(
            name='UserMovieList',
        ),
    ]
