# Generated by Django 3.0.7 on 2020-06-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200620_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(null=True),
        ),
    ]
