# Generated by Django 3.0.7 on 2020-06-20 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200620_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
