# Generated by Django 3.0.7 on 2020-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_remove_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
