# Generated by Django 3.0.7 on 2020-06-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_movie_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
    ]
