# Generated by Django 3.0.7 on 2020-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20200620_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='boxoffice',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbrating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbvotes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
    ]
