# Generated by Django 3.0.7 on 2020-06-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20200620_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='media_type',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbrating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
