# Generated by Django 3.0.7 on 2020-06-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_auto_20200620_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='media_type',
            new_name='type',
        ),
    ]
