# Generated by Django 3.0.7 on 2020-06-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_auto_20200620_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdbrating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
    ]
