# Generated by Django 3.0.7 on 2020-06-20 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
