# Generated by Django 3.0.7 on 2020-06-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_comment_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(default=1),
        ),
    ]
