# Generated by Django 3.0.7 on 2020-06-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_auto_20200620_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie_id',
        ),
    ]
