# Generated by Django 3.0.7 on 2020-06-21 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_auto_20200621_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
