# Generated by Django 3.0.7 on 2020-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_auto_20200621_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
        ),
    ]
