# Generated by Django 3.0.7 on 2020-06-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_auto_20200621_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='id',
        ),
    ]
