# Generated by Django 3.0.7 on 2020-06-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0030_auto_20200621_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='movie_id',
        ),
    ]
