# Generated by Django 3.0.7 on 2020-06-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_auto_20200621_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie_id',
            new_name='id',
        ),
    ]
