# Generated by Django 3.0.7 on 2020-11-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_auto_20201114_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='film',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
    ]
