# Generated by Django 3.0.7 on 2020-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('runtime', models.CharField(max_length=255, null=True)),
                ('reviews', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('directorId', models.IntegerField(null=True)),
                ('categoryId', models.IntegerField(null=True)),
            ],
        ),
    ]
