# Generated by Django 3.1.3 on 2020-11-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('released', models.CharField(max_length=255, null=True)),
                ('runtime', models.CharField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=255, null=True)),
                ('director', models.TextField(null=True)),
                ('plot', models.TextField(null=True)),
                ('poster', models.TextField(null=True)),
            ],
        ),
    ]
